### ISSUE TITLE
Modder credit for Zooming Mars

### ISSUE THREAD

**Issue by Csc-unit** [PhasmaExMachina/destiny-child-mods-archive#6]
Use this form to submit modder author/creator information for a given mod so they get credit for their work:

Link to mod:
https://www.deviantart.com/thecediz/art/Mars-c005-846514316

Name of modder that released the mod: Csc_Unit

Name(s) of modders the mod is based on:

I'll update the information in the archive as soon as I can and will close this ticket when it's done.

**Comment by Csc-unit** [comment]
I changed the link to my page

**Comment by PhasmaExMachina** [comment]
@Csc-unit I think there's been a misunderstanding. This is not to provide a link to where you want people to go, although I'll certainly add that link to your modder profile on the archive soon.

I need the links to any of your mods where they are in the archive (on https://phasmaexmachina.github.io/destiny-child-mods-archive/) in order to see the mod hashes to which to add your name. If you want to link them to this issue I'll update them pretty quickly since I won't have to hunt for them. Otherwise I may figure out which are yours on my own eventually.

**Comment by Csc-unit** [comment]
Hm so I am not very computer savvy. I know that normally it is a direct
download, I thought the link could be changed. If you say the only option
is to provide a link on my modder's profile it's okay I'll do with that.
Do you need me to identify my mods? Would that help?

The said link :
https://www.deviantart.com/thecediz/gallery/72932091/destiny-child-mods

Le sam. 8 août 2020 à 17:58, PhasmaExMachina <notifications@github.com> a
écrit :

**Comment by PhasmaExMachina** [comment]
Yes @Csc-unit , if you could provide direct links to your mods on the archive it would be very helpful. These would be in the following format:

https://phasmaexmachina.github.io/destiny-child-mods-archive/live2d-viewer.html?model=[model-code]&modHash=[hash]&background=%23111

**Comment by PhasmaExMachina** [comment]
I'm pretty much done with csc-unit credits. Closing this for now.

**Comment by Csc-unit** [comment]
Thank you for your work
